### ISSUE TITLE
Use https://pypi.org/project/truststore/

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#977]
Using https://pypi.org/project/truststore/ should enable users with mitm proxy to access conda forge.

**Comment by kariharju** [comment]
With rcc the following dependency level enables this:
```YAML
channels:
  - conda-forge

dependencies:
  - python=3.10.12
  - truststore=0.8.0
  - pip=23.2.1
  - pip:
    - --use-feature=truststore
    - rpaframework==27.0.1
    - robocorp==1.0.0
```
